package com.studybuddy.api.service;

import com.studybuddy.api.api.ApiDtos.*;
import com.studybuddy.api.domain.*;
import com.studybuddy.api.repo.*;
import java.util.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class GroupService {
  private final GroupRepository groups; private final CourseRepository courses; private final MembershipRepository memberships; private final SessionRepository sessions; private final MessageRepository messages; private final ProfileRepository profiles;
  public GroupService(GroupRepository groups,CourseRepository courses,MembershipRepository memberships,SessionRepository sessions,MessageRepository messages,ProfileRepository profiles){this.groups=groups;this.courses=courses;this.memberships=memberships;this.sessions=sessions;this.messages=messages;this.profiles=profiles;}
  @Transactional public GroupResponse create(User user,GroupRequest request){ Course course=courses.findById(request.courseId()).orElseThrow(()->new NoSuchElementException("Course not found.")); StudyGroup group=groups.save(new StudyGroup(course,user,request.name(),request.description(),request.capacity(),request.studyMode())); memberships.save(new GroupMembership(group,user,MembershipStatus.APPROVED,true)); return response(group,user); }
  @Transactional(readOnly=true) public List<GroupResponse> list(User user,Long courseId){ List<StudyGroup> found=courseId==null?groups.findAll():groups.findByCourseId(courseId);return found.stream().map(g->response(g,user)).toList(); }
  @Transactional public void requestJoin(User user,Long groupId){ StudyGroup group=get(groupId); GroupMembership existing=memberships.findByGroupIdAndUserId(groupId,user.getId()).orElse(null); if(existing!=null && existing.getStatus()!=MembershipStatus.LEFT && existing.getStatus()!=MembershipStatus.REMOVED) throw new IllegalArgumentException("You already have a membership request for this group."); if(memberships.countByGroupIdAndStatus(groupId,MembershipStatus.APPROVED)>=group.getCapacity()) throw new IllegalArgumentException("This group is already full."); if(existing==null) memberships.save(new GroupMembership(group,user,MembershipStatus.PENDING,false)); else existing.setStatus(MembershipStatus.PENDING); }
  @Transactional public void decide(User actor,Long groupId,Long membershipId,boolean approve){ requireManage(actor,groupId); GroupMembership membership=memberships.findById(membershipId).orElseThrow(()->new NoSuchElementException("Membership request not found.")); if(!membership.getGroup().getId().equals(groupId)) throw new IllegalArgumentException("Membership request does not belong to this group."); if(membership.getStatus()!=MembershipStatus.PENDING) throw new IllegalArgumentException("Only pending requests can be decided."); if(approve && memberships.countByGroupIdAndStatus(groupId,MembershipStatus.APPROVED)>=membership.getGroup().getCapacity()) throw new IllegalArgumentException("This group is already full."); membership.setStatus(approve?MembershipStatus.APPROVED:MembershipStatus.REJECTED); }
  @Transactional public void leave(User user,Long groupId){ GroupMembership membership=memberships.findByGroupIdAndUserId(groupId,user.getId()).orElseThrow(()->new AccessDeniedException("You are not a member of this group.")); if(membership.isCoordinator()) throw new IllegalArgumentException("Transfer ownership before leaving the group."); membership.setStatus(MembershipStatus.LEFT); }
  @Transactional public SessionResponse createSession(User user,Long groupId,SessionRequest request){ requireManage(user,groupId); if(!request.startsAt().isBefore(request.endsAt())) throw new IllegalArgumentException("Session end time must be after start time."); StudySession session=sessions.save(new StudySession(get(groupId),user,request.startsAt(),request.endsAt(),request.location(),request.virtualUrl(),request.agenda()));return sessionResponse(session); }
  @Transactional(readOnly=true) public List<SessionResponse> sessions(User user,Long groupId){ requireMember(user,groupId);return sessions.findByGroupIdOrderByStartsAtAsc(groupId).stream().map(this::sessionResponse).toList(); }
  @Transactional public MessageResponse addMessage(User user,Long groupId,MessageRequest request){ requireMember(user,groupId);GroupMessage message=messages.save(new GroupMessage(get(groupId),user,request.body()));return messageResponse(message); }
  @Transactional(readOnly=true) public List<MessageResponse> messages(User user,Long groupId){ requireMember(user,groupId);return messages.findByGroupIdOrderByCreatedAtAsc(groupId).stream().map(this::messageResponse).toList(); }
  @Transactional(readOnly=true) public List<GroupMembership> memberships(User user,Long groupId){ requireManage(user,groupId);return memberships.findByGroupId(groupId); }
  public void requireMember(User user,Long groupId){ GroupMembership m=memberships.findByGroupIdAndUserId(groupId,user.getId()).orElseThrow(()->new AccessDeniedException("Group membership required."));if(m.getStatus()!=MembershipStatus.APPROVED) throw new AccessDeniedException("Approved group membership required."); }
  public void requireManage(User user,Long groupId){ GroupMembership m=memberships.findByGroupIdAndUserId(groupId,user.getId()).orElseThrow(()->new AccessDeniedException("Group coordinator role required."));if(m.getStatus()!=MembershipStatus.APPROVED || !m.isCoordinator()) throw new AccessDeniedException("Group coordinator role required."); }
  private StudyGroup get(Long id){return groups.findById(id).orElseThrow(()->new NoSuchElementException("Study group not found."));}
  private GroupResponse response(StudyGroup group,User viewer){ Optional<GroupMembership> membership=memberships.findByGroupIdAndUserId(group.getId(),viewer.getId()); return new GroupResponse(group.getId(),group.getCourse().getId(),group.getCourse().getCode(),group.getName(),group.getDescription(),group.getCapacity(),group.getStudyMode(),group.getOwner().getId(),memberships.countByGroupIdAndStatus(group.getId(),MembershipStatus.APPROVED),membership.map(m->m.getStatus()==MembershipStatus.APPROVED).orElse(false),membership.map(GroupMembership::isCoordinator).orElse(false)); }
  private SessionResponse sessionResponse(StudySession s){return new SessionResponse(s.getId(),s.getStartsAt(),s.getEndsAt(),s.getLocation(),s.getVirtualUrl(),s.getAgenda());}
  private MessageResponse messageResponse(GroupMessage m){String name=profiles.findById(m.getAuthor().getId()).map(StudentProfile::getDisplayName).orElse("Member");return new MessageResponse(m.getId(),m.getAuthor().getId(),name,m.isRemoved()?"[Removed by moderation]":m.getBody(),m.getCreatedAt(),m.isRemoved());}
}
